### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [ahhh/PSSE#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by ahhh** [comment]
Hey Karan! Thank you for your post, it sent me on a journey of understanding software licensees. Please let me know if I got it somewhat correct: http://lockboxx.blogspot.com/2015/10/software-licensing-overview-closed-and.html

Further, I've gone through and licensed all of my original projects, please check them out as well :)
